name: ekart
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase packages
  google_sign_in: ^5.4.1
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  firebase_remote_config: ^3.0.6
  firebase_analytics: ^10.0.6
  firebase_dynamic_links: ^5.0.6

  # State management
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

  # UI
  flutter_screenutil: ^5.6.0
  fluttertoast: ^8.1.1
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+3
  shimmer: ^2.0.0
  lottie: ^2.0.0

  # Services
  url_launcher: ^6.1.6
  pay: ^1.0.11
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_phoenix: ^1.1.0
  package_info_plus: ^3.0.2
  local_auth: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/